/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gianfranco.relojDigital;

import java.util.Date;

/**
 *
 * @author gianf
 */
public class AlarmaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlarmaPanel
     */
    public AlarmaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlarmaHora = new javax.swing.JLabel();
        jSpinnerAlarma = new javax.swing.JSpinner();
        jCheckBoxActiva = new javax.swing.JCheckBox();

        jLabelAlarmaHora.setText("Alarma: ");

        jSpinnerAlarma.setModel(new javax.swing.SpinnerDateModel());

        jCheckBoxActiva.setText("Activa");
        jCheckBoxActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlarmaHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinnerAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxActiva)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlarmaHora)
                    .addComponent(jSpinnerAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxActiva))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo para crear la alarma a partir de lo valores introducidos en el panel
     * @return 
     */
    public Alarma getSelectedValue()
    {
        Date date = (Date)jSpinnerAlarma.getValue();
        boolean activa = jCheckBoxActiva.isSelected();
        return new Alarma(date,activa);
    }
    
    private void jCheckBoxActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActivaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxActiva;
    private javax.swing.JLabel jLabelAlarmaHora;
    private javax.swing.JSpinner jSpinnerAlarma;
    // End of variables declaration//GEN-END:variables
}
