/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NuevaReserva.java
 *
 * Created on 19-oct-2022, 2:10:01
 */
/**
 *
 * @author gianf
 */
public class NuevaReserva extends javax.swing.JDialog {

    /** Creates new form NuevaReserva */
    public NuevaReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanelFestival.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelNombrePersona = new javax.swing.JLabel();
        jTextFieldNombrePersona = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jSeparatorDatospersona = new javax.swing.JSeparator();
        jLabelNuevareserva = new javax.swing.JLabel();
        jLabelFechaEvento = new javax.swing.JLabel();
        jSpinnerFechaEvento = new javax.swing.JSpinner();
        jLabelTipoEvento = new javax.swing.JLabel();
        jComboBoxTipoEvento = new javax.swing.JComboBox();
        jPanelFestival = new javax.swing.JPanel();
        jLabelNdias = new javax.swing.JLabel();
        jTextFieldNdias = new javax.swing.JTextField();
        jLabelPulsera = new javax.swing.JLabel();
        jCheckBoxPulsera = new javax.swing.JCheckBox();
        jLabelNpersonas = new javax.swing.JLabel();
        jTextFieldNpersonas = new javax.swing.JTextField();
        jLabelTipoSsala = new javax.swing.JLabel();
        jComboBoxTipoSala = new javax.swing.JComboBox();
        jButtonReservar = new javax.swing.JButton();
        jSeparatorNreseva = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva reserva");
        setModal(true);
        setResizable(false);

        jLabelNombrePersona.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelNombrePersona.setText("Nombre:");

        jTextFieldNombrePersona.setToolTipText("Nombre de la persona que hace la reserva");
        jTextFieldNombrePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePersonaActionPerformed(evt);
            }
        });

        jLabelApellidos.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jTextFieldApellidos.setToolTipText("Apellidos de la persona que hace la reserva");
        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });

        jLabelTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelTelefono.setText("Teléfono:");

        jTextFieldTelefono.setToolTipText("Teléfono de contacto");

        jLabelNuevareserva.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelNuevareserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevareserva.setText("Nueva reserva");

        jLabelFechaEvento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelFechaEvento.setText("Fecha Evento");

        jSpinnerFechaEvento.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaEvento.setToolTipText("Fecha del evento");

        jLabelTipoEvento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelTipoEvento.setText("Tipo de evento");

        jComboBoxTipoEvento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jComboBoxTipoEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local ensayo", "Concierto", "Festival" }));
        jComboBoxTipoEvento.setToolTipText("Tipo de evento");
        jComboBoxTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEventoActionPerformed(evt);
            }
        });

        jPanelFestival.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos para el festival", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 10))); // NOI18N

        jLabelNdias.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelNdias.setText("Número de días:");

        jTextFieldNdias.setToolTipText("Número de días del festival");
        jTextFieldNdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNdiasActionPerformed(evt);
            }
        });

        jLabelPulsera.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelPulsera.setText("Requiere pulsera");

        jCheckBoxPulsera.setToolTipText("En caso de que sea necesaria pulsera");

        javax.swing.GroupLayout jPanelFestivalLayout = new javax.swing.GroupLayout(jPanelFestival);
        jPanelFestival.setLayout(jPanelFestivalLayout);
        jPanelFestivalLayout.setHorizontalGroup(
            jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFestivalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNdias)
                    .addComponent(jLabelPulsera))
                .addGap(27, 27, 27)
                .addGroup(jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNdias, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPulsera))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanelFestivalLayout.setVerticalGroup(
            jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFestivalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNdias)
                    .addComponent(jTextFieldNdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelFestivalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxPulsera)
                    .addComponent(jLabelPulsera))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabelNpersonas.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelNpersonas.setText("Número de personas: ");

        jTextFieldNpersonas.setToolTipText("Número de asistentes");

        jLabelTipoSsala.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabelTipoSsala.setText("Tipo de sala");

        jComboBoxTipoSala.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jComboBoxTipoSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sala pequeña", "Gran sala", "Evento en patio" }));
        jComboBoxTipoSala.setToolTipText("Elegir el tamaño de la sala");

        jButtonReservar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonReservar.setText("Reservar");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonReservar)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaEvento)
                            .addComponent(jLabelTipoEvento)
                            .addComponent(jLabelNpersonas)
                            .addComponent(jLabelTipoSsala)
                            .addComponent(jLabelApellidos))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelFestival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTipoEvento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerFechaEvento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombrePersona))
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombrePersona)
                            .addComponent(jLabelTelefono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparatorDatospersona)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNuevareserva, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparatorNreseva, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNuevareserva, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparatorNreseva, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePersona)
                    .addComponent(jTextFieldNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorDatospersona, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaEvento)
                    .addComponent(jSpinnerFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoEvento)
                    .addComponent(jComboBoxTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelFestival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNpersonas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoSsala)
                    .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonReservar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNdiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNdiasActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jComboBoxTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEventoActionPerformed
        String tipoEvento;
        tipoEvento = jComboBoxTipoEvento.getSelectedItem().toString();
        if (tipoEvento.equals("Festival"))
            jPanelFestival.setVisible(true);
        else
            jPanelFestival.setVisible(false);
    }//GEN-LAST:event_jComboBoxTipoEventoActionPerformed

    private void jTextFieldNombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePersonaActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JCheckBox jCheckBoxPulsera;
    private javax.swing.JComboBox jComboBoxTipoEvento;
    private javax.swing.JComboBox jComboBoxTipoSala;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelFechaEvento;
    private javax.swing.JLabel jLabelNdias;
    private javax.swing.JLabel jLabelNombrePersona;
    private javax.swing.JLabel jLabelNpersonas;
    private javax.swing.JLabel jLabelNuevareserva;
    private javax.swing.JLabel jLabelPulsera;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoEvento;
    private javax.swing.JLabel jLabelTipoSsala;
    private javax.swing.JPanel jPanelFestival;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorDatospersona;
    private javax.swing.JSeparator jSeparatorNreseva;
    private javax.swing.JSpinner jSpinnerFechaEvento;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNdias;
    private javax.swing.JTextField jTextFieldNombrePersona;
    private javax.swing.JTextField jTextFieldNpersonas;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
